### ISSUE TITLE
Blank lines with single line of output

### ISSUE THREAD

**Issue by rnrobson** [fardad/Submitter#18]
When you configure the submitter to skip blank lines, it fails when there is a single line of output. We have the first IPC144 workshop where they should print "*** Welcome to Seneca's C Programming Course ***\n". This works correctly but if the \n is removed, it says that the output is incorrect. Similarly, if a \n is placed at the start of the line, the submitter says the output is incorrect. This problem occurs ONLY when there is a single line of output. Given multiple lines of output, the submitter works as expected.

**Comment by rnrobson** [comment]
I just checked it on 2 lines and the same issue happens with the following code that was expecting a \n at the end of the last line.

int main(void)
{
        printf("*** Welcome to Seneca's C Programming Course ***\n");
        printf("================================================");
        return 0;
}

**Comment by fardad** [comment]
Fixed
