### ISSUE TITLE
I am having issue for submitting the workshops 

### ISSUE THREAD

**Issue by heta782002** [fardad/Submitter#2]
![image](https://github.com/user-attachments/assets/7e024ab6-4310-4ec0-8dc4-147cfe56ad73)

I am not able to submit the workshop for oop244. the curser is keep blinking after i  hit the submit command can you please help me with it.

thank you 
Heta Nitinkumar Bhagat

**Comment by fardad** [comment]
The fix is applied 
I will inform the professors to update their submitter program

**Comment by heta782002** [comment]
![issue](https://github.com/user-attachments/assets/0636eb62-7c50-459d-9054-3078d29d0fe1)
I hope this message finds you well. 

Thank you for your assistance in resolving the recent issue with my submission. Unfortunately, I am still unable to complete the submission successfully, 

If possible, could you please advise on any alternative methods or additional steps that might help address this issue? I am eager to complete the submission and ensure everything is in order.

Thank you for your time and support.
