### ISSUE TITLE
UTF8 in config files

### ISSUE THREAD

**Issue by corbar** [fardad/Submitter#8]
If I put in the config file UTF-8 characters (like `«...»`), the email created by the submitter is not correct. The problem has been traced to two environmental variables set in `.bashrc`.

```bash
export LC_ALL=C
export LC_COLLATE=C
```

Removing those lines and logout/login fixes the issue.

However, students seem to have difficulties editing `.bashrc`, and at the beginning of the term I seem to spend a few weeks convincing them to make the change.

# Another Fix

It is possible to fix the issue from C++. If you add the following lines in the `main` function of the submitter (just before 'sict::Submitter S(argc, argv);`) the issue goes away.

```cpp
//set new shell environmental variable using putenv
char lc_all[]="LC_ALL=en_CA.UTF-8";
char lc_col[]="LC_COLLATE=en_CA.UTF-8";
putenv( lc_all );
putenv( lc_col );
```

**Comment by fardad** [comment]
Added
